chore: added workspace files
Wavely-project/core pull request #19
Opened 2024-04-12 15:11 UTC by AbdelrahmanEldabsha

Migrations for workspace files
and Apis for (Create workspace, GeWorkspaces)

2024-04-13 08:15 UTC, 7adidaz requested changes

2024-04-13 08:15 UTC, 7adidaz commented on src/api/workspace/workspaceModel.ts
> +// });
remove

2024-04-13 08:15 UTC, 7adidaz commented on src/api/workspace/workspaceRouter.ts
> +})();
Consider adding an **authentication** to the middleware array and create an **authorization** middleware, I tried creating a `workspace` with a different `ownerId` than mine and it worked, the same goes for creating a `channel`. 

I also expect that users outside the `workspace` or `channel` can't retrieve data about the channel, you can use the `members` table to check for access and create a new table representing the `many to many` relationship between users and workspaces, which you can use later as a reference for the authorization step.


```
{
  "success": false,
  "message": "Error creating Workspace: insert into `workspaces` (`avatarUrl`, `description`, `name`, `ownerId`) values ('string', 'string', 'string', 1) - Cannot add or update a child row: a foreign key constraint fails (`wavely`.`workspaces`, CONSTRAINT `workspaces_ownerid_foreign` FOREIGN KEY (`ownerId`) REFERENCES `users` (`id`))",
  "responseObject": null,
  "statusCode": 500
}
```

2024-04-14 13:28 UTC, AbdelrahmanEldabsha commented on src/api/channels/channelController.ts
> +
Its creatorId in db schema, its not like user schema

2024-04-15 04:15 UTC, 7adidaz requested changes

2024-04-15 04:15 UTC, 7adidaz commented on src/api/channels/channelRouter.ts
> +	router.get('/getWorkspaceChannel/:id', AuthController.authenticate, ChannelController.getChannels);
Better is to use `/workspace/:id/channels` looks more restful which will be used and routed by the workspace controller, and of course cancel the `ChannelController.getChannels` controller and use the internal service response with `findAllWorkspaceChannels` 

https://opensource.zalando.com/restful-api-guidelines/#138

2024-04-25 22:02 UTC, merged